artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1QErXWSFqsbLv9DknfwlkPsCXedJuHpYX/view?usp=sharing
  local_data_file: artifacts/data_ingestion/Kidney_stone_dataset.zip
  unzip_dir: artifacts/data_ingestion

prepare_model:
  root_dir: artifacts/prepare_model
  base_model_path: artifacts/prepare_model/base_model.h5
  updated_base_model_path: artifacts/prepare_model/base_model_updated.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  training_data: artifacts/data_ingestion/Kidney Stone Dataset/Augmented Dataset
  log_dir: logs/runtime_logs.log